# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
#if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
#  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
#fi

source "$HOME/.config/zsh/env.zsh"
source "$HOME/.config/zsh/nnn_preview_setup.zsh"

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=5000
SAVEHIST=5000
HISTDUP=erase
setopt appendhistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups

bindkey -e

# Home / End keys
bindkey '\e[H' beginning-of-line      # Home
bindkey '\e[F' end-of-line            # End

# Delete key
bindkey '\e[3~' delete-char           # Delete under cursor

# Ctrl + Left/Right to move by word
bindkey '^[[1;5C' forward-word        # Ctrl+Right
bindkey '^[[1;5D' backward-word       # Ctrl+Left

# Ctrl + Backspace and Ctrl + Delete to delete word
bindkey '^H' backward-kill-word       # Ctrl+Backspace (may already work)
bindkey '^[[3;5~' kill-word           # Ctrl+Delete

bindkey '^[[A' history-search-backward
bindkey '^[[B' history-search-forward



zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
zstyle ':completion:*' menu select
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"

autoload -U compinit && compinit
# source ~/.fzf-tab/fzf-tab.plugin.zsh

source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme

if [[ -n "$DISPLAY" || -n "$WAYLAND_DISPLAY" ]]; then
  # Graphical terminal (GUI)
  [[ -f ~/.config/zsh/p10k.gui.zsh ]] && source /home/marttave/.config/zsh/p10k.gui.zsh
else
  # TTY
  [[ -f ~/.config/zsh/p10k.tty.zsh ]] && source /home/marttave/.config/zsh/p10k.tty.zsh
fi

function y() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		builtin cd -- "$cwd"
	fi
	rm -f -- "$tmp"
}

export PATH=/opt/cuda/bin:$PATH
export LD_LIBRARY_PATH=/opt/cuda/lib64:$LD_LIBRARY_PATH


source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

# Set up fzf key bindings and fuzzy completion
source <(fzf --zsh)

# Aliases
alias lg="git log --all  --decorate --oneline --graph"
alias open="xdg-open"
alias zed="zeditor"
alias ls='ls --color -al'
alias s="kitten ssh"
alias monitor-reset="pkill kanshi && hyprctl dispatch exec kanshi"

export SSH_AUTH_SOCK=$HOME/.bitwarden-ssh-agent.sock

eval "$(zoxide init zsh)"

# Swift install
. "/home/marttave/.local/share/swiftly/env.sh"
