USB_EXCLUDE_PHONE=1

run-on-bat hyprctl "keyword animations:enabled 0"
run-on-bat hyprctl "keyword decoration:blur:enabled 0"

run-on-ac hyprctl "keyword animations:enabled 1"
run-on-ac hyprctl "keyword decoration:blur:enabled 1"
