preload = /home/marttave/.config/hypr/wallpapers/wallpaper_1
preload = /home/marttave/.config/hypr/wallpapers/wallpaper_2
preload = /home/marttave/.config/hypr/wallpapers/wallpaper_3
preload = /home/marttave/.config/hypr/wallpapers/wallpaper_4

wallpaper ,/home/marttave/.config/wallpapers/wallpaper_3
