# Aliases :
alias lg="git log --all  --decorate --oneline --graph"
alias open="xdg-open"

# Need wireguard to work
alias wgup="sudo wg-quick up wg0"
alias wgdown="sudo wg-quick down wg0"
alias pi="wgup;ssh pi@192.168.50.1"


# Theme working with low skill terminal :
if [ "$TERM" = "linux" ]; then
    ZSH_THEME="robbyrussell"
else
    ZSH_THEME="powerlevel10k/powerlevel10k"
fi

# Plugins ::
plugins=(
        git
        zsh-syntax-highlighting
        fast-syntax-highlighting
        web-search
        sudo
        ufw
        copypath
)