monitor=DP-1,preferred,1920x-1080,1.2
monitor=, 1920x1080, auto-right,1
monitor=desc:Samsung Electric Company LC34G55T H4ZRB02457, preferred, -760x-1440 , 1



workspace = 1, persistent:true, monitor:eDP-1
workspace = 2, persistent:true, monitor:eDP-1
workspace = 3, persistent:true, monitor:eDP-1
workspace = 4, persistent:true, monitor:eDP-1
workspace = 5, persistent:true, monitor:eDP-1
workspace = 6, persistent:true, monitor:HDMI-A-1 
workspace = 7, persistent:true, monitor:HDMI-A-1
workspace = 8, persistent:true, monitor:HDMI-A-1
workspace = 9, persistent:true, monitor:HDMI-A-1
workspace = 10, persistent:true, monitor:HDMI-A-1

