include tokyonight_night.conf

# BEGIN_KITTY_FONTS
font_family      family="MesloLGL Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

clipboard_control write-clipboard write-primary no-append

map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

copy_on_select yes

mouse_map right press ungrabbed paste_from_clipboard

map ctrl+shift+1 change_font_size current +2.0
map ctrl+shift+plus change_font_size current +2.0
map ctrl+minus change_font_size current -2.0
map ctrl+0 change_font_size current 0

# First value is vertical, second is horizontal
window_padding_width 0 3

confirm_os_window_close 0

enabled_layouts horizontal
allow_remote_control yes
