# On new client
[Interface]
PrivateKey=[Insert private key]
# Adress to take when connected to vpn
Address=192.168.50.4
# Dns to use
DNS=8.8.8.8,8.8.4.4

[Peer]
# Public key of raspi
PublicKey=[Insert pi public key]
# = All ip should pass through vpn
AllowedIPs=0.0.0.0/0
# Public raspi ip
EndPoint=178.237.86.224:51820

